version: '3'
services:
  m-business-app:
    image: postgres:15.3
    container_name: business-app-db
    #restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=your-username
      - POSTGRES_PASSWORD=your-password
    volumes:
      - ./postgres:/var/lib/postgresql/data