-- AddForeignKey
ALTER TABLE "FICHAS_INSCRIPCION" ADD CONSTRAINT "FICHAS_INSCRIPCION_FicSocCod_fkey" FOREIGN KEY ("FicSocCod") REFERENCES "SOCIOS"("SocCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FICHAS_INSCRIPCION" ADD CONSTRAINT "FICHAS_INSCRIPCION_FicDepCod_fkey" FOREIGN KEY ("FicDepCod") REFERENCES "TIPOS_DEPORTE"("DepCod") ON DELETE RESTRICT ON UPDATE CASCADE;
