-- AlterTable
ALTER TABLE "FICHAS_INSCRIPCION" ALTER COLUMN "FicEstReg" SET DEFAULT 'A';

-- AlterTable
ALTER TABLE "SOCIOS" ALTER COLUMN "SocEstReg" SET DEFAULT 'A';

-- AlterTable
ALTER TABLE "TIPOS_DEPORTE" ALTER COLUMN "DepEstReg" SET DEFAULT 'A';
